### ISSUE TITLE
unidentified C++ exception when reassigning entities to variables

### ISSUE THREAD

**Issue by fabiansinz** [G-Node/nixpy#78] opened 2014-10-07 14:26 UTC
I came across this error, when I looped over several files, extracted data_arrays from them, and assigned them to the same variable. 

Setting them to None solved the problem. 

````
HDF5-DIAG: Error detected in HDF5 (1.8.11) thread 139774801626944:
  #000: ../../../src/H5A.c line 2589 in H5Aexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: ../../../src/H5Gloc.c line 195 in H5G_loc(): invalid group ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.11) thread 139774801626944:
  #000: ../../../src/H5A.c line 2589 in H5Aexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: ../../../src/H5Gloc.c line 195 in H5G_loc(): invalid group ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.8.11) thread 139774801626944:
  #000: ../../../src/H5A.c line 551 in H5Aopen(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: ../../../src/H5Gloc.c line 195 in H5G_loc(): invalid group ID
    major: Invalid arguments to routine
    minor: Bad value
Traceback (most recent call last):
  File "detect_peak_troughs_hdf5.py", line 47, in <module>
    print trough_array
RuntimeError: unidentifiable C++ exception
````

**Comment by jgrewe** [comment] 2015-02-03 10:58
I checked the reassignment with the current nix version and was not able to reproduce it any more. I thus, close this bug.

**Closed by jgrewe** 2015-02-03 10:58 UTC
Labels: bug
