### ISSUE TITLE
Building for Python 3.6 from git repo (Ubuntu 16.04)

### ISSUE THREAD

**Issue by msuzen** [G-Node/nixpy#243] opened 2017-02-17 16:11 UTC

**Comment by achilleas-k** [comment] 2017-02-17 16:14
This is essentially a duplicate of #211. The setup script detects nix and immediately tries to build the bindings. If boost-python isn't installed (for the specific version of Python), it will fail.

The setup script should try to detect everything required to build the bindings and simply build without the bindings if any step fails.

**Closed** 2019-01-18 16:48 UTC
