### ISSUE TITLE
Lots of compilation warnings

### ISSUE THREAD

**Issue by s0nskar** [G-Node/nixpy#246] opened 2017-03-01 15:11 UTC
While installing `nix dev,` I got lots of compilation warning. Which should be fixed. I am attaching paste of all warnings. [Pastebin](http://pastebin.com/2vRPN3pB)

**Comment by achilleas-k** [comment] 2017-03-01 15:34
Dupe of #219

**Closed** 2019-01-18 16:47 UTC
Labels: duplicate
